[theme]
base = "light"
primaryColor = "#80571E"
backgroundColor = "#FFF9E9"
secondaryBackgroundColor = "#FFF3D2"
textColor = "#2B2924"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
